### ISSUE TITLE
Standalone won't start if previously used project directory disappears

### ISSUE THREAD

**Issue by tjohnman** [zedapp/zed#503]
If the local directory project Zed was working on the last time is umounted, deleted, or otherwise removed, the program will hang at startup showing only the logo on an empty window.

Tested on standalone Mac OS X with a remote FTP server mounted via Transmit.

I believe only the last three lines of the attached output are relevant to this issue.

```
2015-02-13 13:53:37.057 node-webkit[7380:191471] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2015-02-13 13:53:37.264 node-webkit Helper[7381:191520] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2015-02-13 13:53:37.364 node-webkit Helper[7382:191539] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
Checking for update 
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
Caught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
http://requirejs.org/docs/errors.html#scripterror[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135337:INFO:CONSOLE(32)] "Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror", source: app://./dep/require.js (32)
[7380:0213/135338:INFO:CONSOLE(97)] ""Architect resolved"", source: app://./js/boot.js (97)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded eventbus"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded ui"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded keys"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded db"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded history"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded windows"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded webserver"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded token_store"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(161)] ""Loaded background"", source: app://./js/boot.js (161)
[7380:0213/135338:INFO:CONSOLE(102)] ""Architect createApp error" {"stack":"Error: ENOENT, no such file or directory '/Volumes/ftp.e3th.net/public_html/e3th.net/eixam'\n    at Object.fs.statSync (fs.js:676:18)\n    at Object.plugin [as setup] (app://./js/fs/node.js:19:28)\n    at Architect.registerPlugin (app://./dep/architect.js:488:20)\n    at next (app://./dep/architect.js:468:17)\n    at register (app://./dep/architect.js:531:13)\n    at Object.plugin [as setup] (app://./js/background.nw.js:27:9)\n    at Architect.registerPlugin (app://./dep/architect.js:488:20)\n    at next (app://./dep/architect.js:468:17)\n    at register (app://./dep/architect.js:531:13)\n    at Object.plugin [as setup] (app://./js/token_store.nw.js:29:9)","errno":-2,"code":"ENOENT","path":"/Volumes/ftp.e3th.net/public_html/e3th.net/eixam","syscall":"stat"} "Error: ENOENT, no such file or directory '/Volumes/ftp.e3th.net/public_html/e3th.net/eixam'\n    at Object.fs.statSync (fs.js:676:18)\n    at Object.plugin [as setup] (app://./js/fs/node.js:19:28)\n    at Architect.registerPlugin (app://./dep/architect.js:488:20)\n    at next (app://./dep/architect.js:468:17)\n    at register (app://./dep/architect.js:531:13)\n    at Object.plugin [as setup] (app://./js/background.nw.js:27:9)\n    at Architect.registerPlugin (app://./dep/architect.js:488:20)\n    at next (app://./dep/architect.js:468:17)\n    at register (app://./dep/architect.js:531:13)\n    at Object.plugin [as setup] (app://./js/token_store.nw.js:29:9)"", source: app://./js/boot.js (102)
[7380:0213/135338:INFO:CONSOLE(164)] ""Error" {"stack":"Error: ENOENT, no such file or directory '/Volumes/ftp.e3th.net/public_html/e3th.net/eixam'\n    at Object.fs.statSync (fs.js:676:18)\n    at Object.plugin [as setup] (app://./js/fs/node.js:19:28)\n    at Architect.registerPlugin (app://./dep/architect.js:488:20)\n    at next (app://./dep/architect.js:468:17)\n    at register (app://./dep/architect.js:531:13)\n    at Object.plugin [as setup] (app://./js/background.nw.js:27:9)\n    at Architect.registerPlugin (app://./dep/architect.js:488:20)\n    at next (app://./dep/architect.js:468:17)\n    at register (app://./dep/architect.js:531:13)\n    at Object.plugin [as setup] (app://./js/token_store.nw.js:29:9)","errno":-2,"code":"ENOENT","path":"/Volumes/ftp.e3th.net/public_html/e3th.net/eixam","syscall":"stat"}", source: app://./js/boot.js (164)
[7380:0213/135338:INFO:CONSOLE(81)] ""Error" {"stack":"Error: ENOENT, no such file or directory '/Volumes/ftp.e3th.net/public_html/e3th.net/eixam'\n    at Object.fs.statSync (fs.js:676:18)\n    at Object.plugin [as setup] (app://./js/fs/node.js:19:28)\n    at Architect.registerPlugin (app://./dep/architect.js:488:20)\n    at next (app://./dep/architect.js:468:17)\n    at register (app://./dep/architect.js:531:13)\n    at Object.plugin [as setup] (app://./js/background.nw.js:27:9)\n    at Architect.registerPlugin (app://./dep/architect.js:488:20)\n    at next (app://./dep/architect.js:468:17)\n    at register (app://./dep/architect.js:531:13)\n    at Object.plugin [as setup] (app://./js/token_store.nw.js:29:9)","errno":-2,"code":"ENOENT","path":"/Volumes/ftp.e3th.net/public_html/e3th.net/eixam","syscall":"stat"}", source: app://./js/boot.js (81)
```

**Comment by zefhemel** [comment]
What version you

**Comment by ryanpcmcquen** [comment]
I still receive the top part of this error on 1.1.0 (standalone Linux):

```
http://requirejs.org/docs/errors.html#scripterrorCaught exception: Error: Script error
```

Full output:
https://gist.github.com/ryanpcmcquen/d8dfe3c441f282af2c8d
OR:
http://sprunge.us/HOPI

This happens with a project that has _not_ disappeared.
